name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    env:
      MSBUILDSINGLELOADCONTEXT: 1
    steps:
    - uses: actions/checkout@v2
    - name: Use dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Use dotnet-format
      run: dotnet tool update -g --version 3.2.* dotnet-format >nul || dotnet tool list -g
    - name: Run dotnet-format
      run: dotnet format -f . --dry-run --check -v:diag
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Start storage emulator
      run: |
        "%ProgramFiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" init /server "(localdb)\MsSqlLocalDb"
        "%ProgramFiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator" start
    - name: Test
      run: dotnet test --no-restore
      env:
        LuisAppId: ${{ secrets.LuisAppId }}
        LuisAppSlot: staging
        LuisEndpoint: https://nosayudamos-lu.cognitiveservices.azure.com/
        LuisSubscriptionKey: ${{ secrets.LuisSubscriptionKey }}
        TextAnalysisEndpoint: https://nosayudamos-ta.cognitiveservices.azure.com/
        TextAnalysisSubscriptionKey: ${{ secrets.TextAnalysisSubscriptionKey }}
        StorageConnectionString: ${{ secrets.StorageConnectionString }}
    - name: Log
      run: dir log.txt -s | gc
      shell: pwsh
