name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Use dotnet-format
      run: dotnet tool update -g --version 3.2.* dotnet-format >nul || dotnet tool list -g
    - name: Run dotnet-format
      run: dotnet format -f . --dry-run --check -v:diag
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -v:m
    - name: Test
      run: dotnet test --no-restore -v:m
      env:
        LuisAppId: ${{ secrets.LuisAppId }}
        LuisAppSlot: staging
        LuisEndpoint: https://nosayudamos-lu.cognitiveservices.azure.com/
        LuisSubscriptionKey: ${{ secrets.LuisSubscriptionKey }}
        TextAnalysisEndpoint: https://nosayudamos-ta.cognitiveservices.azure.com/
        TextAnalysisSubscriptionKey: ${{ secrets.TextAnalysisSubscriptionKey }}
        StorageConnectionString: ${{ secrets.StorageConnectionString }}
