name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    env:
      MSBUILDSINGLELOADCONTEXT: 1
    steps:
    - uses: actions/checkout@v2
    - name: Use dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Use dotnet-format
      run: dotnet tool update -g --version 3.2.* dotnet-format >nul || dotnet tool list -g
    - name: Run dotnet-format
      run: dotnet format -f . --dry-run --check -v:diag
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Start storage emulator
      run: |
        "%ProgramFiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" init /server "(localdb)\MsSqlLocalDb"
        "%ProgramFiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator" start
    - name: Test
      run: dotnet test --no-build -- xunit.parallelizeAssembly=false xunit.parallelizeTestCollections=false
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    - name: Log
      run: dir log.txt -s | gc
      shell: pwsh
